### ISSUE TITLE
Make failure message great again

### ISSUE THREAD

**Issue by lizhemingi** [containers/youki#150]
Right now if we had a test failed when run `cargo test`, the failure message is missing and we can not locate the assert that failed directly.  

**And if comment the tests code in `tty.rs`, the failure message show up again. Just like the failure message is eaten by the tty.**

Failure test without commenting tests in tty.rs.
![image](https://user-images.githubusercontent.com/9639449/125227109-d6ea8480-e304-11eb-91e9-865f2ae397f0.png)

Failure test with commenting tests in tty.rs.
![image](https://user-images.githubusercontent.com/9639449/125227181-fbdef780-e304-11eb-8100-f26a29903d74.png)

It would be a little annoying for debugging when CI failed. So maybe we should find a way to make failure message come back.

cc @utam0k

**Comment by yihuaf** [comment]
@utam0k I wasn't sure if you want to add `--nocapture` to `cargo test` on CI as a solution? This issue is asking for that.

**Comment by utam0k** [comment]
> @utam0k I wasn't sure if you want to add `--nocapture` to `cargo test` on CI as a solution? This issue is asking for that.

That may be fine for CI, but what about local execution unit tests...

**Comment by yihuaf** [comment]
Sorry I don't follow. For local unit test, you also run `cargo test -- --nocapture` to see the error output in case test fails when developing. It works exactly the same.

**Comment by duduainankai** [comment]
@utam0k @yihuaf 

I think `nocapture` can not meet the requirement of this issue.

https://doc.rust-lang.org/cargo/commands/cargo-test.html#display-options

It seems that the `nocapture` option means `do not capture the output of our tested binary`, something like `println` in our code.

But this issue is looking for the output information by `rust test`, something like which assert in which file is failed (The difference between two screenshots in the description.)

But maybe add `nocapture` to CI is also a good advice.

**Comment by utam0k** [comment]
I agree with this. However, I don't think this is the root solution.
> But maybe add nocapture to CI is also a good advice.
