### ISSUE TITLE
Enable running youki with cargo

### ISSUE THREAD

**Issue by Will-Shanks** [containers/youki#1562]
Since youki is now published on crates.io (#586) it is possible to run `cargo install youki` to install youki into cargo's bin dir, but since it is called `youki` not `cargo-youki` one is unable to run it as a cargo sub command `cargo youki ...`

**Comment by YJDoc2** [comment]
Hey @Will-Shanks , as mentioned in the PR, let us discuss here the reasoning behind this.
As it stands, youki is a low level runtime to be used either by some higher level runtime, such as docker etc, or  if one wants, then directly by user. In that way, as you have mentioned, user can install youki through cargo as it is available on crates.io, and use it as a command,eg `youki -h`.

My understanding is that cargo-* commands are usually for things that are directly related to cargo, or setup/compilation of rust projects. In that sense, youki should not become a cargo sub-command, as it is not related to either of those.

Further, doing this change will likely require a breaking release, as we are changing binary name, and would not make sense where only youki is used, eg, directly downloaded as a binary , without having cargo on system.

Can you explain your reasoning behind  this request so that we can understand it better and come up with a possible solution?

Thanks :)

**Comment by Will-Shanks** [comment]
The reason is it makes `youki` simpler for me to use :) For reasons I don't think are worth getting into,  I am unable to add my cargo bin dir to my path, so being able to call youki through cargo gets rid of some headaches for me. I figured it's a small, harmless change  that makes my life easier, and could be useful for others too.

This would not be a breaking change, if you look at my PR, cargo create two binaries, one called `youki` and another called `cargo-youki` so this would have no effect on any existing workflows that expect a `youki` binary,  similar to what [flamegraph](https://github.com/flamegraph-rs/flamegraph/blob/main/Cargo.toml#L12) does.

I wasn't expecting so much push back, is there a reason this behavior is undesirable that I'm missing? As far as I can tell all this does is add convenience without any detrimental effect.

**Comment by utam0k** [comment]
Thanks for your comment. The question is how many people will use this. It does not matter whether it will affect the current behavior. In OSS, once a feature is added, the maintainer, not the person who created the feature, has to maintain and take it into account all the time. Therefore, we need to consider how many people will find this useful and convenient.

**Comment by Will-Shanks** [comment]
Fair enough, I guess I'll look at taking my project in a different direction. 

Thanks!
