### ISSUE TITLE
Use `clone(2)` instead of `fork(2)`

### ISSUE THREAD

**Issue by utam0k** [containers/youki#1601]
# Why?

We have to need to use `CLONE_PARENT` but unfortunately `fork(2)` doesn't support it.
Without CLONE_PARENT, the init process becomes a zombie process and no one can `wait(2)`.
For example, it is a problem when trying to implement the exec and wait commands.

**Comment by utam0k** [comment]
ref: https://github.com/containers/youki/pull/217

**Comment by utam0k** [comment]
ref: https://github.com/opencontainers/runc/blob/5a0642d6fd0a7c217c1cd6fd472b72b36820caff/libcontainer/nsenter/nsexec.c#L389-L398

**Comment by utam0k** [comment]
ref: https://stackoverflow.com/questions/33404939/how-to-call-fork-with-flags-or-clone-without-the-first-argument-fn

**Comment by yihuaf** [comment]
Wanna me to take a look at this?

**Comment by yihuaf** [comment]
@utam0k I thought a bit more on this subject and here is my understanding. Currently, your observation is correct that the container init process is orphaned to pid 1 when the youki intermediate process exits. This is normal behavior, but this means no one will wait on the init process.

Here is what I think how it should work. Consider we have the `caller of youki`, `youki main process`, `intermediate` and `container init` process. The end result we want to see is that the container init process is re-parent to the `caller of youki` instead of pid 1 in the detached mode. In the foreground mode, we want `youki main process` to wait on the `container init` process.

If we agree that the the above is the result we want, there are a few ways to achieve this. The first one, without using CLONE_PARENT, is for the youki main process to set itself as the `PR_SET_CHILD_SUBREAPER`. In this way, when the intermediate process terminates, the container init process is re-parented to the youki main process.

Another way is to clone the intermediate process as the child of the youki main process. The intermediate process can then clone the container init process as a sibling process with CLONE_PARENT. Then, youki main process becomes the parent of the container init process. There is no need to use `PR_SET_CHILD_SUBREAPER`.

Here are some other edge cases. I don't think we should clone both the intermediate process and the container init using CLONE_PARENT. The end result will be both the intermediate process and container init process becomes children of the `caller of youki`. Based on what I read, the `caller of youki` (containerd-shim or conmon) is expected to to use `PR_SET_CHILD_SUBREAPER`. Or same as `runc`, if caller doesn't set the sub-reaper flag, the container init process will reparent to pid 1 after youki main process exits.

The reason we can do this because `runc` launches multiple processes (`runc run` calls `runc init` calls nsexec.c and etc.). So `runc` needs a bit more dance to achieve this, but we only have 3 processes in total.

I should be able to have a PR ready soon, but can you check my work in the meantime and this is inline of your understanding? Thanks :)

**Comment by utam0k** [comment]
@yihuaf I thout the same thing you suggest before. I am agree with you :100: How about implementing the run command as the test for CLONE_PARENT?
BTW how about crun? As far as I know, crun doesn't need the init subcommand runc has.

**Comment by yihuaf** [comment]
I will check with `crun` code just to make sure.

You can review #1637 when you have a chance. I went ahead and implemented CLONE_PARENT and the tests are passing. The detached mode should work as expected with that PR. I was planning a follow up PR to fix the foreground mode. the `youki run` currently defaults to detached mode, so I was planning to fix that with the foregound mode.

**Comment by utam0k** [comment]
@yihuaf I'll check your PR on my local today.
