### ISSUE TITLE
Does youki check if the default values are valid when they are displayed?

### ISSUE THREAD

**Issue by unknowndevQwQ** [containers/youki#1684]
The options for runc to display default values are --log-format, --root, --rootless, of which only the --root option default value is controlled by XDG_RUNTIME_DIR.

The` --root` option of youki has the following default values.
`/run/youki` for the rootful mode option
`{XDG_RUNTIME_DIR}/youki` when the `XDG_RUMTIME_DIR` environment variable is present
`/run/user/{uid}/youki` as a backup when `XDG_RUMTIME_DIR` is not available
`/run/user/{uid}` as a fallback if it does not exist `{HOME}/.youki/run`
`/tmp/youki-{uid}` when none of the above is available

Should I check that every possible value is actually available (path exists and has permission to operate) before trying to display the default values? Or should we show `XDG_RUNTIME_DIR/youki` if it exists and `/run/youki` if it doesn't, like runc does?

Other things that need to show default values are much simpler, but there is still a problem: should I get the default values from clap or should youki store the default values?

**Comment by yihuaf** [comment]
After some considerations, I don't think it is worth the efforts to display the dynamic defaults for `--root` in the help page. First, it is not clear now `claps` are supporting this usecase. Second, the logic to compute the root path resides inside `youki` crate while the command line options are defined in `liboci-cli`. It doesn't make much sense because this is a `youki` specific behavior, not a `liboci-cli` behavior. The users of `liboci-cli` can freely to choose what the default scheme for the `--root` flag should be.
