### ISSUE TITLE
Github action error: Error when evaluating 'strategy' for job 'check'. 

### ISSUE THREAD

**Issue by yihuaf** [containers/youki#284]
```
Error when evaluating 'strategy' for job 'check'. (Line: 30, Col: 15): Matrix vector 'dirs' does not contain any values
```

First observed in https://github.com/containers/youki/actions/runs/1210634803.

The change is a readme change, so likely it is not caused by the PR.

**Comment by YJDoc2** [comment]
Yes , it is not caused by the PR itself.
The reason behind it is :

currently the CI first runs a job called `changes` which checks which specific directories have changed : https://github.com/containers/youki/blob/main/.github/workflows/main.yml#L10-L23

This maps the files changed according to path and maps them to provided values, which in our case are directories. These values are given as output by this job.

The job `check` depends on `changes`, and uses the output of it as matrix to run the format and lint checks only in those directories in which the files have changed. Reasoning behind this, is that if only the files in cgroups have changed, then there is no need to run checks in youki or test_framework etc. Note that this only applies to format and lint checks, all tests are always run.

In this particular case, no files in any of the given path patterns had changed, so output of `changes` was empty. Thus the matrix given to the `check` was also empty, which resulted in the error. The fix on this would be to put some kind of condition such that set the matrix only if the output is non-empty, otherwise not run the job, but I'm not sure how to do that.
