### ISSUE TITLE
Be published crate.io

### ISSUE THREAD

**Issue by utam0k** [containers/youki#586]
- [ ] license or license-file 
- [ ] description 
- [ ] homepage 
- [ ] documentation 
- [ ] repository 
- [ ] readme

**Comment by utam0k** [comment]
https://doc.rust-lang.org/cargo/reference/publishing.html

> Check out the [metadata you can specify](https://doc.rust-lang.org/cargo/reference/manifest.html) in Cargo.toml to ensure your crate can be discovered more easily! Before publishing, make sure you have filled out the following fields:
> 
> [license or license-file](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields)
> [description](https://doc.rust-lang.org/cargo/reference/manifest.html#the-description-field)
> [homepage](https://doc.rust-lang.org/cargo/reference/manifest.html#the-homepage-field)
> [documentation](https://doc.rust-lang.org/cargo/reference/manifest.html#the-documentation-field)
> [repository](https://doc.rust-lang.org/cargo/reference/manifest.html#the-repository-field)
> [readme](https://doc.rust-lang.org/cargo/reference/manifest.html#the-readme-field)

**Comment by Silcet** [comment]
Hi @utam0k . I'm interested in taking this task because I want to use youki in a project I'm working on and I'd instead pull it from crates than from GitHub. However, the part I'm mostly interested in is taking the commands of the youki crate and turning them into a library so they can be used from a different main. 

Would that part interest you too? If so, should we just make another issue and tackle that there?

**Comment by utam0k** [comment]
@Silcet Sorry for the late reply. Currently, youki is already divided into several crates. What crate do you want to use?

**Comment by YJDoc2** [comment]
Closing this, given that we have published several version now 😂
